"""Migração inicial

Revision ID: cfee15c0aa8f
Revises: d586c532e4a8
Create Date: 2024-11-14 12:12:52.461677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cfee15c0aa8f'
down_revision = 'd586c532e4a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faturamento', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('forma_pagamento', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('data', sa.Date(), nullable=False))
        batch_op.drop_constraint('aluno_email_key', type_='unique')
        batch_op.drop_column('email')

    with op.batch_alter_table('artesanato', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)

    with op.batch_alter_table('gasto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor', sa.Float(), nullable=False))
        batch_op.alter_column('data',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gasto', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('valor')

    with op.batch_alter_table('artesanato', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('aluno_email_key', ['email'])
        batch_op.drop_column('data')
        batch_op.drop_column('forma_pagamento')
        batch_op.drop_column('faturamento')

    # ### end Alembic commands ###
